### ISSUE TITLE
snmp v1 without bulkrequests for mikrotik

### ISSUE THREAD

**Issue by rostchri** [paulstuart/influxsnmp#22]
I'm using mikrotik switches RB260GSP. Unfortunately this device only supports snmp v1.
So a bulk-request does not work.

Example:
Trying to use influxsnmp with following config:

```
 ...
 [snmp "switch"]
 host      = 192.168.178.2
 community = public
 port      = 161
 timeout   = 20
 freq      = 30
 version   = 1
 ...
```

leads to 

```
12:29:29.682005 IP (tos 0x0, ttl 64, id 37333, offset 0, flags [none], proto UDP (17), length 70)
    192.168.178.33.57949 > 192.168.178.2.161: [udp sum ok]  { SNMPv1 { GetBulk(27) [v2 PDU in v1 message]} 
```

which is not answered by the switch ...

```
2016/05/30 13:06:37 error sampling host 192.168.178.2: Request timeout (after 0 retries)
```

But this one works: snmpwalk -v1  -c public 192.168.178.2
This is using GetNextRequest which is answered correctly:

```
12:29:54.869186 ARP, Ethernet (len 6), IPv4 (len 4), Request who-has 192.168.178.2 tell 192.168.178.33, length 28
12:29:54.871454 ARP, Ethernet (len 6), IPv4 (len 4), Reply 192.168.178.2 is-at e4:8d:8c:f9:1b:c3, length 46
12:29:54.871493 IP (tos 0x0, ttl 64, id 23354, offset 0, flags [none], proto UDP (17), length 68)
    192.168.178.33.53318 > 192.168.178.2.161: [udp sum ok]  { SNMPv1 { GetNextRequest(25) R=1574203751  .1.3.6.1.2.1 } } 
12:29:54.872796 IP (tos 0x0, ttl 255, id 848, offset 0, flags [none], proto UDP (17), length 79)
    192.168.178.2.161 > 192.168.178.33.53318: [udp sum ok]  { SNMPv1 { GetResponse(36) R=1574203751  .1.3.6.1.2.1.1.1.0="RB260GSP" } } 
12:29:54.873098 IP (tos 0x0, ttl 64, id 60851, offset 0, flags [none], proto UDP (17), length 71)
    192.168.178.33.53318 > 192.168.178.2.161: [udp sum ok]  { SNMPv1 { GetNextRequest(28) R=1574203752  .1.3.6.1.2.1.1.1.0 } } 
12:29:54.874148 IP (tos 0x0, ttl 255, id 1104, offset 0, flags [none], proto UDP (17), length 79)
```

Is it possible to modify influxsnmp so that snmp-v1 does NOT use bulkrequests?

**Comment by paulstuart** [comment]
I've updated snmputil to walk vs. bulkwalk if it's snmp v1. No device to test on - let me know if this does the trick.

**Comment by rostchri** [comment]
Thanks for the quick reply :)

Unfortunately it is not working...
I'm doing my first steps with influxsnmp and I'm using these options at the moment: 

```
influxsnmp  -config config.cfg -verbose -sample
```

Doing this func Sampler is used which executes the bulkWalker, so I still see the following snmp-communication: { SNMPv1 { GetBulk(29) [v2 PDU in v1 message]}, which is not accepted by the switch.

And if I understand the following code correctly, BulkWalk is executed in the first place too ...
Or is here some kind of lazy code-execution in place?

```
    // snmp v1 doesn't support bulkwalk
    walk := client.BulkWalk
    if p.Version == "1" {
        walk = client.Walk
    }
```

I tried to test the func Poller by doing: influxsnmp  -config config.cfg -verbose 
but this fails before any snmp-communication can take place.
I think this is due to some kind of configuration-error, which I'm not able to find at the moment... 

```
panic: unable to decode json: received status code 405 err: invalid character 'M' looking for beginning of value

goroutine 1 [running]:
panic(0x473b40, 0xc8202a8690)
    /usr/local/opt/go/libexec/src/runtime/panic.go:481 +0x3e6
main.getSenders(0xc820012600)
    /Users/chr/.go/src/github.com/paulstuart/influxsnmp/main.go:130 +0x113
main.main()
    /Users/chr/.go/src/github.com/paulstuart/influxsnmp/main.go:444 +0x3a7
```

Here some more infos:

snmpwalk -v1  -c public 192.168.178.2

```
SNMPv2-MIB::sysDescr.0 = STRING: RB260GSP
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.14988.2
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (3724991) 10:20:49.91
SNMPv2-MIB::sysContact.0 = STRING: 
SNMPv2-MIB::sysName.0 = STRING: MikroTik
SNMPv2-MIB::sysLocation.0 = STRING: 
SNMPv2-MIB::sysServices.0 = INTEGER: 2
IF-MIB::ifNumber.0 = INTEGER: 6
IF-MIB::ifIndex.1 = INTEGER: 1
IF-MIB::ifIndex.2 = INTEGER: 2
IF-MIB::ifIndex.3 = INTEGER: 3
IF-MIB::ifIndex.4 = INTEGER: 4
IF-MIB::ifIndex.5 = INTEGER: 5
IF-MIB::ifIndex.6 = INTEGER: 6
IF-MIB::ifDescr.1 = STRING: Port1
IF-MIB::ifDescr.2 = STRING: Port2
IF-MIB::ifDescr.3 = STRING: Port3
IF-MIB::ifDescr.4 = STRING: Port4
IF-MIB::ifDescr.5 = STRING: Port5
IF-MIB::ifDescr.6 = STRING: SFP
IF-MIB::ifType.1 = INTEGER: ethernetCsmacd(6)
IF-MIB::ifType.2 = INTEGER: ethernetCsmacd(6)
IF-MIB::ifType.3 = INTEGER: ethernetCsmacd(6)
IF-MIB::ifType.4 = INTEGER: ethernetCsmacd(6)
IF-MIB::ifType.5 = INTEGER: ethernetCsmacd(6)
IF-MIB::ifType.6 = INTEGER: ethernetCsmacd(6)
IF-MIB::ifMtu.1 = INTEGER: 1500
IF-MIB::ifMtu.2 = INTEGER: 1500
IF-MIB::ifMtu.3 = INTEGER: 1500
IF-MIB::ifMtu.4 = INTEGER: 1500
IF-MIB::ifMtu.5 = INTEGER: 1500
IF-MIB::ifMtu.6 = INTEGER: 1500
IF-MIB::ifSpeed.1 = Gauge32: 1000000000
IF-MIB::ifSpeed.2 = Gauge32: 1000000000
IF-MIB::ifSpeed.3 = Gauge32: 1000000000
IF-MIB::ifSpeed.4 = Gauge32: 1000000000
IF-MIB::ifSpeed.5 = Gauge32: 1000000000
IF-MIB::ifSpeed.6 = Gauge32: 10000000
IF-MIB::ifPhysAddress.1 = STRING: e4:8d:8c:f9:1b:c3
IF-MIB::ifPhysAddress.2 = STRING: e4:8d:8c:f9:1b:c3
IF-MIB::ifPhysAddress.3 = STRING: e4:8d:8c:f9:1b:c3
IF-MIB::ifPhysAddress.4 = STRING: e4:8d:8c:f9:1b:c3
IF-MIB::ifPhysAddress.5 = STRING: e4:8d:8c:f9:1b:c3
IF-MIB::ifPhysAddress.6 = STRING: e4:8d:8c:f9:1b:c3
IF-MIB::ifAdminStatus.1 = INTEGER: up(1)
IF-MIB::ifAdminStatus.2 = INTEGER: up(1)
IF-MIB::ifAdminStatus.3 = INTEGER: up(1)
IF-MIB::ifAdminStatus.4 = INTEGER: up(1)
IF-MIB::ifAdminStatus.5 = INTEGER: up(1)
IF-MIB::ifAdminStatus.6 = INTEGER: down(2)
IF-MIB::ifOperStatus.1 = INTEGER: up(1)
IF-MIB::ifOperStatus.2 = INTEGER: up(1)
IF-MIB::ifOperStatus.3 = INTEGER: up(1)
IF-MIB::ifOperStatus.4 = INTEGER: down(2)
IF-MIB::ifOperStatus.5 = INTEGER: down(2)
IF-MIB::ifOperStatus.6 = INTEGER: down(2)
IF-MIB::ifLastChange.1 = Timeticks: (192) 0:00:01.92
IF-MIB::ifLastChange.2 = Timeticks: (3556) 0:00:35.56
IF-MIB::ifLastChange.3 = Timeticks: (3575) 0:00:35.75
IF-MIB::ifLastChange.4 = Timeticks: (0) 0:00:00.00
IF-MIB::ifLastChange.5 = Timeticks: (0) 0:00:00.00
IF-MIB::ifLastChange.6 = Timeticks: (0) 0:00:00.00
IF-MIB::ifInOctets.1 = Counter32: 390241535
IF-MIB::ifInOctets.2 = Counter32: 66537323
IF-MIB::ifInOctets.3 = Counter32: 10099296
IF-MIB::ifInOctets.4 = Counter32: 0
IF-MIB::ifInOctets.5 = Counter32: 0
IF-MIB::ifInOctets.6 = Counter32: 0
IF-MIB::ifInUcastPkts.1 = Counter32: 452502
IF-MIB::ifInUcastPkts.2 = Counter32: 380844
IF-MIB::ifInUcastPkts.3 = Counter32: 19585
IF-MIB::ifInUcastPkts.4 = Counter32: 0
IF-MIB::ifInUcastPkts.5 = Counter32: 0
IF-MIB::ifInUcastPkts.6 = Counter32: 0
IF-MIB::ifInNUcastPkts.1 = Counter32: 54445
IF-MIB::ifInNUcastPkts.2 = Counter32: 34568
IF-MIB::ifInNUcastPkts.3 = Counter32: 3809
IF-MIB::ifInNUcastPkts.4 = Counter32: 0
IF-MIB::ifInNUcastPkts.5 = Counter32: 0
IF-MIB::ifInNUcastPkts.6 = Counter32: 0
IF-MIB::ifInDiscards.1 = Counter32: 0
IF-MIB::ifInDiscards.2 = Counter32: 0
IF-MIB::ifInDiscards.3 = Counter32: 0
IF-MIB::ifInDiscards.4 = Counter32: 0
IF-MIB::ifInDiscards.5 = Counter32: 0
IF-MIB::ifInDiscards.6 = Counter32: 0
IF-MIB::ifInErrors.1 = Counter32: 0
IF-MIB::ifInErrors.2 = Counter32: 0
IF-MIB::ifInErrors.3 = Counter32: 0
IF-MIB::ifInErrors.4 = Counter32: 0
IF-MIB::ifInErrors.5 = Counter32: 0
IF-MIB::ifInErrors.6 = Counter32: 0
IF-MIB::ifInUnknownProtos.1 = Counter32: 0
IF-MIB::ifInUnknownProtos.2 = Counter32: 0
IF-MIB::ifInUnknownProtos.3 = Counter32: 0
IF-MIB::ifInUnknownProtos.4 = Counter32: 0
IF-MIB::ifInUnknownProtos.5 = Counter32: 0
IF-MIB::ifInUnknownProtos.6 = Counter32: 0
IF-MIB::ifOutOctets.1 = Counter32: 74958832
IF-MIB::ifOutOctets.2 = Counter32: 390421251
IF-MIB::ifOutOctets.3 = Counter32: 14545058
IF-MIB::ifOutOctets.4 = Counter32: 0
IF-MIB::ifOutOctets.5 = Counter32: 0
IF-MIB::ifOutOctets.6 = Counter32: 0
IF-MIB::ifOutUcastPkts.1 = Counter32: 387564
IF-MIB::ifOutUcastPkts.2 = Counter32: 441584
IF-MIB::ifOutUcastPkts.3 = Counter32: 20933
IF-MIB::ifOutUcastPkts.4 = Counter32: 0
IF-MIB::ifOutUcastPkts.5 = Counter32: 0
IF-MIB::ifOutUcastPkts.6 = Counter32: 0
IF-MIB::ifOutNUcastPkts.1 = Counter32: 38992
IF-MIB::ifOutNUcastPkts.2 = Counter32: 58855
IF-MIB::ifOutNUcastPkts.3 = Counter32: 89613
IF-MIB::ifOutNUcastPkts.4 = Counter32: 0
IF-MIB::ifOutNUcastPkts.5 = Counter32: 0
IF-MIB::ifOutNUcastPkts.6 = Counter32: 0
IF-MIB::ifOutDiscards.1 = Counter32: 0
IF-MIB::ifOutDiscards.2 = Counter32: 0
IF-MIB::ifOutDiscards.3 = Counter32: 0
IF-MIB::ifOutDiscards.4 = Counter32: 0
IF-MIB::ifOutDiscards.5 = Counter32: 0
IF-MIB::ifOutDiscards.6 = Counter32: 0
IF-MIB::ifOutErrors.1 = Counter32: 0
IF-MIB::ifOutErrors.2 = Counter32: 0
IF-MIB::ifOutErrors.3 = Counter32: 0
IF-MIB::ifOutErrors.4 = Counter32: 0
IF-MIB::ifOutErrors.5 = Counter32: 0
IF-MIB::ifOutErrors.6 = Counter32: 0
End of MIB
```

config.cfg (I'm sure this is incomplete...)

```
[common]
httpPort   = 8085
mibs = IF-MIB:SNMPv2-MIB
mibfile = /tmp/if.json
elapsed = true

[snmp "switch"]
host      = 192.168.178.2
community = public
port      = 161
timeout   = 20
freq      = 30
version   = 1

[mibs "switch"]
name = sysName

[influx "*"]
url        = http://192.168.178.9:8086
database   = db1
```

```
influxsnmp  -config config.cfg -verbose -dump -filter  > /tmp/if.json
2016/05/30 23:11:14 poller error: no OID found for sysName
```

/tmp/if.json looks fine to me. Here the beginning of the file:

```
{
   "Name": "SNMPv2-SMI::mgmt",
   "OID": ".1.3.6.1.2",
   "Syntax": "",
   "Default": "",
   "Hint": "",
   "Index": "",
   "Units": "",
   "Access": "",
   "Augments": "",
   "Status": "",
   "Description": ""
 }
{
   "Name": "IF-MIB::ifType",
   "OID": ".1.3.6.1.2.1.2.2.1.3",
...
```

**Comment by paulstuart** [comment]
the first assignment is of the function pointer itself, not the results of
executing it. The pointer is updated to "Walk" if the version is "1".

I've somewhat eviscerated verbose functionality, I'll review to see if we
can suss out what's (not) happening here. Should have something by
tomorrow.

**Comment by paulstuart** [comment]
I found and fixed a bug with snmputil that was filtering out all if.\* OIDs. Try updating and rebuilding.

**Comment by rostchri** [comment]
No change.

influxsnmp  -config config.cfg -verbose -sample 
leads to a GetBulk-snmp communication : { SNMPv1 { GetBulk(29) [v2 PDU in v1 message]}

and

influxsnmp  -config config.cfg -verbose
still crash before any snmp-communication can happen

```
panic: unable to decode json: received status code 405 err: invalid character 'M' looking for beginning of value

goroutine 1 [running]:
panic(0x473b40, 0xc8201156c0)
    /usr/local/opt/go/libexec/src/runtime/panic.go:481 +0x3e6
main.getSenders(0xc820013790)
    /Users/chr/.go/src/github.com/paulstuart/influxsnmp/main.go:130 +0x113
main.main()
    /Users/chr/.go/src/github.com/paulstuart/influxsnmp/main.go:444 +0x3a7
```

I changed the getSenders() - code temporarily to:

```
func getSenders() map[string]Sender {
        s := map[string]Sender{}
        for name, c := range cfg.Influx {
                sender, err := makeSender(c)
                fmt.Println(err)
                //if err != nil {
                //      panic(err)
                //}
                s[name] = sender
        }
        return s
}
```

After that I got:

```
influxsnmp  -config config.cfg -verbose
unable to decode json: received status code 405 err: invalid character 'M' looking for beginning of value
Web interface:
http://192.168.88.2:8085
http://192.168.178.33:8085
panic: Request timeout (after 10 retries)

goroutine 21 [running]:
panic(0x473c20, 0xc820528090)
    /usr/local/opt/go/libexec/src/runtime/panic.go:481 +0x3e6
main.gather(0x0, 0xc820013a10, 0xd, 0xc820013cb0, 0x6, 0xc820114760, 0x1, 0xa1, 0x3c, 0xa, ...)
    /Users/chr/.go/src/github.com/paulstuart/influxsnmp/main.go:328 +0x46c
created by main.main
    /Users/chr/.go/src/github.com/paulstuart/influxsnmp/main.go:457 +0x7b2
```

So the snmp-communication started now and i see that { SNMPv1 { GetBulk(29) [v2 PDU in v1 message]} is used. So walk = client.Walk does not eliminate the bulkrequest ...

**Comment by paulstuart** [comment]
The library does an initial walk to determine column names, aliases, operating status, etc. That has been fixed to conditionally not bulkwalk as well.

Update your repos, rebuild and let me know...

**Comment by rostchri** [comment]
Ok i did the following changes:

```
diff --git a/main.go b/main.go
index 66378e2..d65a574 100644
--- a/main.go
+++ b/main.go
@@ -126,9 +126,10 @@ func getSenders() map[string]Sender {
        s := map[string]Sender{}
        for name, c := range cfg.Influx {
                sender, err := makeSender(c)
-               if err != nil {
-                       panic(err)
-               }
+               //if err != nil {
+               //      panic(err)
+               //}
+               fmt.Println("### getSender error: ", err)
                s[name] = sender
        }
        return s
@@ -295,6 +296,7 @@ func gather(send Sender, p snmp.Profile, crit snmp.Criteria, mibID string) {
        } else {
                sender = func(name string, tags map[string]string, value interface{}, ts snmp.TimeStamp) error {
                        values := map[string]interface{}{"value": value}
+                        fmt.Println("### gather ", name, tags, values, ts.Stop)
                        return send(name, tags, values, ts.Stop)
                }
        }
```

And i have the following config now:

```
[common]
httpPort   = 8085
mibs = IF-MIB:SNMPv2-MIB
mibfile = /tmp/if.json
elapsed = false

[snmp "switch"]
host      = 192.168.178.2
community = public
port      = 161
timeout   = 60
freq      = 30
version   = 1
mibs      = mikrotik-sysName mikrotik-ifOutOctets mikrotik-ifInOctets

[mibs "mikrotik-sysName"]
name = sysName

[mibs "mikrotik-ifOutOctets"]
name = ifOutOctets

[mibs "mikrotik-ifInOctets"]
name = ifInOctets

[influx "*"]
url        = http://192.168.178.9:8086
database   = db1
```

Good news the sample-code is working now:

```
influxsnmp  -config config.cfg -verbose -sample
Host:192.168.178.2 Name:sysName Value:MikroTik (string/10.823919ms) Tags:
Host:192.168.178.2 Name:ifOutOctets Value:3406092254 (uint32/32.70353ms) Tags:
Host:192.168.178.2 Name:ifOutOctets Value:639378914 (uint32/32.772991ms) Tags:
Host:192.168.178.2 Name:ifOutOctets Value:3140971545 (uint32/32.838298ms) Tags:
Host:192.168.178.2 Name:ifOutOctets Value:0 (uint32/32.856362ms) Tags:
Host:192.168.178.2 Name:ifOutOctets Value:0 (uint32/32.890227ms) Tags:
Host:192.168.178.2 Name:ifOutOctets Value:0 (uint32/32.907843ms) Tags:
Host:192.168.178.2 Name:ifInOctets Value:3713174805 (uint32/33.964709ms) Tags:
Host:192.168.178.2 Name:ifInOctets Value:3168575152 (uint32/33.985602ms) Tags:
Host:192.168.178.2 Name:ifInOctets Value:239535522 (uint32/34.000572ms) Tags:
Host:192.168.178.2 Name:ifInOctets Value:0 (uint32/34.013001ms) Tags:
Host:192.168.178.2 Name:ifInOctets Value:0 (uint32/34.024848ms) Tags:
Host:192.168.178.2 Name:ifInOctets Value:0 (uint32/34.036188ms) Tags:
```

So the snmp-communication without bulk-requests is working now...

But following is crashing: influxsnmp  -config config.cfg -verbose

```
### getSender error:  check for database db1 failed: unable to decode json: received status code 405 err: invalid character 'M' looking for beginning of value
Web interface:
http://192.168.88.2:8085
http://192.168.178.33:8085
http://10.4.0.2:8085
### gather  sysName map[host:192.168.178.2] map[value:MikroTik] 2016-06-01 15:01:27.843171645 +0200 CEST
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x8de3]

goroutine 10 [running]:
panic(0x497da0, 0xc8200120e0)
    /usr/local/opt/go/libexec/src/runtime/panic.go:481 +0x3e6
main.gather.func2(0xc8201fbf2c, 0x7, 0xc82012d560, 0x3d4660, 0xc82012f880, 0xecee0d3a7, 0xc8322bf190, 0x79e4c0, 0xecee0d3a7, 0x3241c73d, ...)
    /Users/chr/.go/src/github.com/paulstuart/influxsnmp/main.go:300 +0x373
github.com/paulstuart/snmputil.IntegerSender.func1(0xc8201fbf2c, 0x7, 0xc82012d560, 0x3d4660, 0xc82012f880, 0xecee0d3a7, 0xc8322bf190, 0x79e4c0, 0xecee0d3a7, 0x3241c73d, ...)
    /Users/chr/.go/src/github.com/paulstuart/snmputil/senders.go:135 +0x1a4
github.com/paulstuart/snmputil.bulkColumns.func8(0xc820135560, 0x12, 0xc82015ad04, 0x3c34c0, 0xc820135580, 0x0, 0x0)
    /Users/chr/.go/src/github.com/paulstuart/snmputil/poller.go:287 +0xa82
github.com/soniah/gosnmp.(*GoSNMP).walk(0xc8202c8000, 0xc82012e1a1, 0xc82015ade0, 0x10, 0xc8202c6500, 0x0, 0x0)
    /Users/chr/.go/src/github.com/soniah/gosnmp/walk.go:69 +0x88b
github.com/soniah/gosnmp.(*GoSNMP).Walk(0xc8202c8000, 0xc82015ade0, 0x10, 0xc8202c6500, 0x0, 0x0)
    /Users/chr/.go/src/github.com/soniah/gosnmp/gosnmp.go:345 +0x50
github.com/soniah/gosnmp.(*GoSNMP).Walk-fm(0xc82015ade0, 0x10, 0xc8202c6500, 0x0, 0x0)
    /Users/chr/.go/src/github.com/paulstuart/snmputil/poller.go:371 +0x4c
github.com/paulstuart/snmputil.Poller(0xc820013b90, 0xd, 0xc820013e30, 0x6, 0xc8201188e0, 0x1, 0xa1, 0x3c, 0x0, 0x0, ...)
    /Users/chr/.go/src/github.com/paulstuart/snmputil/poller.go:397 +0x512
main.gather(0x0, 0xc820013b90, 0xd, 0xc820013e30, 0x6, 0xc8201188e0, 0x1, 0xa1, 0x3c, 0x0, ...)
    /Users/chr/.go/src/github.com/paulstuart/influxsnmp/main.go:328 +0x431
created by main.main
    /Users/chr/.go/src/github.com/paulstuart/influxsnmp/main.go:458 +0x7b2
```

One part of the problem seems to be my influxdb-database on 192.168.178.9.
This is a influxdb version 0.9.6.1 (https://github.com/rostchri/docker-influxdb).
Here is a communication-dump of the communication between influxsnmp (using above command) and my influxdb:

```
tcpdump -nvv -s 0 -A -i en0 host 192.168.178.9
tcpdump: listening on en0, link-type EN10MB (Ethernet), capture size 262144 bytes
... 
GET /ping HTTP/1.1
Host: influxdb:8086
User-Agent: InfluxDBClient
Accept-Encoding: gzip

...

POST /query?db=&q=show+databases HTTP/1.1
Host: influxdb:8086
User-Agent: InfluxDBClient
Content-Length: 0
Content-Type: 
Accept-Encoding: gzip

...

HTTP/1.1 405 Method Not Allowed
Allow: GET, OPTIONS
Content-Type: text/plain; charset=utf-8
Date: Wed, 01 Jun 2016 13:09:02 GMT
Content-Length: 19

Method Not Allowed
```

So i tried that manually:
curl -i -H "Accept: application/json" 'http://192.168.178.9:8086/query?db=&q=show+databases'  

```
HTTP/1.1 200 OK
Content-Type: application/json
Request-Id: dab87d55-27fa-11e6-9ec2-000000000000
X-Influxdb-Version: 0.9.6.1
Date: Wed, 01 Jun 2016 13:15:04 GMT
Content-Length: 114

{"results":[{"series":[{"name":"databases","columns":["name"],"values":[["collectdb1"],["db1"],["_internal"]]}]}]}
```

curl -i -H "Accept: application/json" -X POST  'http://192.168.178.9:8086/query?db=&q=show+databases'

```
HTTP/1.1 405 Method Not Allowed
Allow: OPTIONS, GET
Content-Type: text/plain; charset=utf-8
Date: Wed, 01 Jun 2016 13:18:42 GMT
Content-Length: 19

Method Not Allowed
```

POST /query?db=&q=show+databases HTTP/1.1 is obviously not allowed in my influxdb-version ...
And the error-message is not presented in json-format..

**Comment by paulstuart** [comment]
Are you deeply tied to that version? So many changes since then and they're just about stable now.

**Comment by rostchri** [comment]
which version of influxdb will work?

**Comment by paulstuart** [comment]
I believe the client works with 0.10.x and up. They're currently at 0.13
and intimating that the next version is 1.0.
I'm using 0.13 now and it seems to be "good enough". The biggest issue I
had with older versions was derivatives in continuous queries (for all the
SNMP counters to be converted into rates.

**Comment by rostchri** [comment]
Ok i'm at influxdb version 0.13 now and it works (0.12 does not work!)
I've the following configuration now:

```
common]
httpPort   = 8085
mibs = IF-MIB:SNMPv2-MIB
mibfile = /tmp/if.json
elapsed = false

[snmp "switch"]
host      = 192.168.178.2
community = public
port      = 161
timeout   = 20
freq      = 30
version   = 1
mibs      = mikrotik-ifDescr mikrotik-ifOutOctets mikrotik-ifInOctets
tags      = ifDescr

[mibs "mikrotik-ifDescr"]
name = ifDescr

[mibs "mikrotik-ifOutOctets"]
name = ifOutOctets

[mibs "mikrotik-ifInOctets"]
name = ifInOctets

[influx "*"]
url        = http://influxdb:8086
database   = snmp1
```

influxsnmp  -config config.cfg -verbose -sample

```
Host:192.168.178.2 Name:ifInOctets Value:1810002268 (uint32/22.723794ms) Tags:
Host:192.168.178.2 Name:ifInOctets Value:2935626168 (uint32/22.790418ms) Tags:
Host:192.168.178.2 Name:ifInOctets Value:353534675 (uint32/22.809101ms) Tags:
Host:192.168.178.2 Name:ifInOctets Value:6402 (uint32/22.823071ms) Tags:
Host:192.168.178.2 Name:ifInOctets Value:0 (uint32/22.835918ms) Tags:
Host:192.168.178.2 Name:ifInOctets Value:0 (uint32/22.847139ms) Tags:
Host:192.168.178.2 Name:ifOutOctets Value:3285766376 (uint32/22.827141ms) Tags:
Host:192.168.178.2 Name:ifDescr Value:Port1 (string/21.512152ms) Tags:
Host:192.168.178.2 Name:ifOutOctets Value:2935065698 (uint32/22.866639ms) Tags:
Host:192.168.178.2 Name:ifOutOctets Value:3278759279 (uint32/22.890712ms) Tags:
Host:192.168.178.2 Name:ifOutOctets Value:1702807 (uint32/22.901517ms) Tags:
Host:192.168.178.2 Name:ifOutOctets Value:0 (uint32/22.91831ms) Tags:
Host:192.168.178.2 Name:ifOutOctets Value:0 (uint32/22.939158ms) Tags:
Host:192.168.178.2 Name:ifDescr Value:Port2 (string/21.554893ms) Tags:
Host:192.168.178.2 Name:ifDescr Value:Port3 (string/21.73048ms) Tags:
Host:192.168.178.2 Name:ifDescr Value:Port4 (string/21.765692ms) Tags:
Host:192.168.178.2 Name:ifDescr Value:Port5 (string/21.774145ms) Tags:
Host:192.168.178.2 Name:ifDescr Value:SFP (string/21.781451ms) Tags:
```

influxsnmp  -config config.cfg -verbose

```
Web interface:
http://192.168.88.2:8085
http://192.168.178.33:8085
http://10.0.0.236:8085
...
```

So the basic stuff is working now. GREAT 👍 

What I don't understand now is how to use the regexp-, alias- and tag-feature for my switch?
I'm interested in ifOutOctets- and ifInOctets-values of all ports, but i want to distinguish between the ports!

You can see that the switch have 5 ports which have a ifDescr (See the complete snmpwalk-output in a former comment too). 

So influxsnmp can read the ifOutOctets- and ifInOctets-counters successfully, but they are stored only with the host:192.168.178.2 - mapping. This is not enough to distinguish the ports. How can i add the port-mapping too?

**Comment by paulstuart** [comment]
Hmmm... it should be automatically pulling ifName and setting the tag "column" for each respective entry. Likewise, ifAlias entries should be saved as "alias" tags. (this is what the other bulkwalk action was doing).

From the walk output above, it doesn't look like they exist. Let me take a whack adding descriptions.

**Comment by paulstuart** [comment]
Updated github.com/paulstuart/snmputil. Do the needful and let me know.

**Comment by rostchri** [comment]
Great it is working now 👍 

config:
[common]
httpPort   = 8085
mibs = IF-MIB:SNMPv2-MIB
mibfile = /tmp/if.json
elapsed = false

[snmp "switch"]
host      = 192.168.178.3
community = public
port      = 161
timeout   = 20
freq      = 30
version   = 1
retries   = 3
mibs      = mikrotik-ifOutOctets mikrotik-ifInOctets

[mibs "mikrotik-ifOutOctets"]
name = ifOutOctets

[mibs "mikrotik-ifInOctets"]
name = ifInOctets

```
influxsnmp -config config.cfg -sample -verbose
Host:192.168.178.3 Name:ifInOctets Value:1121535413 (uint32/14.649226ms) Tags:descr=Port1
Host:192.168.178.3 Name:ifInOctets Value:3102991433 (uint32/14.707919ms) Tags:descr=Port2
Host:192.168.178.3 Name:ifInOctets Value:549165973 (uint32/14.723072ms) Tags:descr=Port3
Host:192.168.178.3 Name:ifInOctets Value:411345136 (uint32/14.734515ms) Tags:descr=Port4
Host:192.168.178.3 Name:ifInOctets Value:11961846 (uint32/14.745845ms) Tags:descr=Port5
Host:192.168.178.3 Name:ifInOctets Value:0 (uint32/14.756698ms) Tags:descr=SFP
Host:192.168.178.3 Name:ifOutOctets Value:3641184254 (uint32/15.040532ms) Tags:descr=Port1
Host:192.168.178.3 Name:ifOutOctets Value:3839297602 (uint32/15.069168ms) Tags:descr=Port2
Host:192.168.178.3 Name:ifOutOctets Value:1780267060 (uint32/15.082837ms) Tags:descr=Port3
Host:192.168.178.3 Name:ifOutOctets Value:401404259 (uint32/15.094365ms) Tags:descr=Port4
Host:192.168.178.3 Name:ifOutOctets Value:5784171 (uint32/15.105401ms) Tags:descr=Port5
Host:192.168.178.3 Name:ifOutOctets Value:0 (uint32/15.116261ms) Tags:descr=SFP
```

My next device is a mikrotik router. We will see ... ;)

Thank you!

**Comment by paulstuart** [comment]
Cool! I'm going to close this now. I'll try and get the config info better annotated (and looking to move to TOML as well).
